name = "satscoinsv-blog"
compatibility_date = "2026-01-29"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"  # Esto hace el fallback automático a index.html

# Opcional: si quieres que el Worker ejecute código antes de assets
# run_worker_first = true  # o un array de paths
